name: Mobile &amp; Web Messaging
title: Mobile &amp; Web Messaging
author :
  name : Jeff Mesnil
  email : jmesnil@gmail.com
  github : jmesnil
  twitter : jmesnil
  url: http://jmesnil.net/about/

profiles: 
  production: 
    base_url: http://mobile-web-messaging.net/
    deploy: 
      host: github_pages 
