name: Mobile and Web Messaging
title: Mobile and Web Messaging
author :
  name : Jeff Mesnil
  email : jmesnil@gmail.com
  github : jmesnil
  twitter : jmesnil
  url: http://jmesnil.net/about/
base_url: ''
